### ISSUE TITLE
things board sevrer down ? 

### ISSUE THREAD

**Issue by guiguitt** [guiguitt/gateway_ttn-thingsboard#3]
@ddorch
the thingsboard server no longer responds to the request either with this script or directly with insomnia. 
I can't find the problem.

**Comment by DDorch** [comment]
Which request?

It's seem to be OK right now and during the last hour:

![image](https://user-images.githubusercontent.com/14124454/60274865-28c83980-98f9-11e9-9562-d4270bd35acd.png)

**Comment by DDorch** [comment]
For your information, the log of the script running on the thingsboard server as a service (See #1):

```
● gateway_ttn.service - Gateway between TTN and Thingsboard
   Loaded: loaded (/etc/systemd/system/gateway_ttn.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2019-06-27 16:26:52 CEST; 14min ago
 Main PID: 17699 (python3)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/gateway_ttn.service
           └─17699 python3 /home/gateway_ttn//GateWay_TTNThingsboard/gateway_ttn_thing.py

juin 27 16:41:31 aubes env[17699]: 2019/06/27 16:41:31: Recept message MQTT...
juin 27 16:41:31 aubes env[17699]: 2019/06/27 16:41:31: Topic : supagrohydraulique/devices/5b228c00-878d-11e9-9807-af0bb1a11174/up
juin 27 16:41:31 aubes env[17699]: 2019/06/27 16:41:31: data: {'latitude': 43.781, 'longitude': 4.56, 'detection': 0}
juin 27 16:41:31 aubes env[17699]: 2019/06/27 16:41:31: send to ThingsBoard
juin 27 16:41:31 aubes env[17699]: 2019/06/27 16:41:31: 1/9 - send request to Acess Token
juin 27 16:41:36 aubes env[17699]: 2019/06/27 16:41:36: Recept message MQTT...
juin 27 16:41:36 aubes env[17699]: 2019/06/27 16:41:36: Topic : supagrohydraulique/devices/5b228c00-878d-11e9-9807-af0bb1a11174/up
juin 27 16:41:36 aubes env[17699]: 2019/06/27 16:41:36: data: {'latitude': 43.781, 'longitude': 4.56, 'detection': 0}
juin 27 16:41:36 aubes env[17699]: 2019/06/27 16:41:36: send to ThingsBoard
juin 27 16:41:36 aubes env[17699]: 2019/06/27 16:41:36: 1/9 - send request to Acess Token
```

The process seems blocked at the step 1/9 of the communication with ThingsBoard. It could be due to the frequency of the MQTT messages (every 5 to 10 seconds) which not give time to the process to end before the next MQTT message received.

I say that because, we don't even have the error message in the console.

**Comment by DDorch** [comment]
This code is wrong for me:

``` python
    while True:
        try:
            printlog("1/9 - send request to Acess Token")
            ResponseAcessToken = requests.post(dPrm['THINGS']['url']+'/api/auth/login/public', headers=headers_AcessT, data=dPrm['THINGS']['publicid'])
            printlog("2/9 - Request response: " + ResponseAcessToken.text)
        except requests.exceptions.RequestException as e:
            printlog("Request response: " + ResponseAcessToken.text)
            continue
```
The while True loop will loop forever if there is no exception. Considering the exception, I'm not sure the requests.exceptions.RequestException is the good trigger to follow.

I think that the connection failed for some reason but we don't raise the good error so we cannot see it.

**Comment by guiguitt** [comment]
Yes, I went through that hypothesis.
But the problem remains when I give him time and with my previous versions. Moreover when I make the request with "insomnia" the server does not send me anything back
![image](https://user-images.githubusercontent.com/guiguitt/photo/blob/master/insomnia.PNG

**Comment by DDorch** [comment]
You should at least get a time out error if the good exception is raised...

**Comment by DDorch** [comment]
Remove the "while True loop" and replace "requests.exceptions.requestException" by "Exception". Replace the "continue" by "return" in order to exit from the function if something wrong append instead of continuing the next steps.

**Comment by guiguitt** [comment]
Okay, I'll try.
